[project]
name = "Messiah"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "typer (>=0.15.2,<0.16.0)",
    "beautifulsoup4 (>=4.13.3,<5.0.0)",
    "requests>=2.32.5",
    "tqdm>=4.67.1",
    "dotenv>=0.9.9",
]
